type: "hartmann_6D"
lipschitz_constant: 8.94
noise_lvl: 0.013887
domain_size: 6
domain_bounds: 
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
  - [0, 1]
safety_threshold: 0.1 # safety threshold
optimum: 1